name: AI Intel Bot (Email+TTS)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"   # 09:00 PKT
    - cron: "0 12 * * *"  # 17:00 PKT

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create service account key file
        shell: bash
        run: |
          if [ -n "${{ secrets.GCP_SA_BASE64 }}" ]; then
            echo "${{ secrets.GCP_SA_BASE64 }}" | base64 -d > sa.json
          else
            printf '%s' '${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}' > sa.json
          fi
          python - <<'PY'
          import json; print("USING SERVICE ACCOUNT:", json.load(open('sa.json'))['client_email'])
          PY
      - name: Run bot
        env:
          GCP_SERVICE_ACCOUNT_JSON_FILE: ${{ github.workspace }}/sa.json
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          GMAIL_TO: ${{ secrets.GMAIL_TO }}
          ATTACH_TTS: true
          DIGEST_TOP_N: "3"
          FEEDS_FILE: config/feeds.yaml
        run: python src/main.py
